name: Generate Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Install package
        run: make install
      
      - name: Create documentation
        run: |
          cd docs
          pip install -r requirements.txt
          make html
      
      - name: Commit documentation changes
        run: |
          git config --global user.email "github-action@github.com"
          git config --global user.name "GithubAction"
          git clone "https://${{github.actor}}:${{github.token}}@github.com/sarodz/sample_model_deployment.git" --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git add .
          git commit -m "update documentation" -a || true
          # Above command fails if no changes are present so we ignore the returned code

      - name: Push changes
        run: |
          cd gh-pages
          git push -f origin gh-pages
        if: github.event_name != 'pull_request'
